import { useState, useRef, useCallback } from "react";
import { Sheet, SheetContent } from "@brands/components/ui/sheet";
import { Button } from "@brands/components/ui/button";
import { Sparkles, Download, Printer, RefreshCw, AlertCircle } from "lucide-react";
import { customFetch } from "@workspace/api-client-react";

interface Props {
  adId?: string;
  adTitle?: string;
}

// ─── Markdown-like renderer ────────────────────────────────────────────────────
function renderInline(text: string): React.ReactNode {
  const parts = text.split(/(\*\*[^*]+\*\*)/g);
  return (
    <>
      {parts.map((part, i) =>
        part.startsWith("**") && part.endsWith("**")
          ? <strong key={i} className="font-semibold text-foreground">{part.slice(2, -2)}</strong>
          : part
      )}
    </>
  );
}

function RenderSummary({ text, streaming }: { text: string; streaming: boolean }) {
  const lines = text.split("\n");
  const nodes: React.ReactNode[] = [];
  let listBuf: React.ReactNode[] = [];

  const flushList = () => {
    if (listBuf.length) {
      nodes.push(<ul key={`ul-${nodes.length}`} className="my-2 space-y-1 pl-4 list-disc">{listBuf}</ul>);
      listBuf = [];
    }
  };

  lines.forEach((line, i) => {
    const isBullet = line.startsWith("- ") || line.startsWith("* ");
    const isNumbered = /^\d+\.\s/.test(line);

    if (!isBullet && !isNumbered) flushList();

    if (line.startsWith("# ")) {
      nodes.push(<h1 key={i} className="text-xl font-bold mt-5 mb-2 text-foreground border-b pb-1">{line.slice(2)}</h1>);
    } else if (line.startsWith("## ")) {
      nodes.push(<h2 key={i} className="text-base font-bold mt-4 mb-1.5 text-foreground">{line.slice(3)}</h2>);
    } else if (line.startsWith("### ")) {
      nodes.push(<h3 key={i} className="text-sm font-semibold mt-3 mb-1 text-foreground/80">{line.slice(4)}</h3>);
    } else if (isBullet) {
      listBuf.push(<li key={i} className="text-sm leading-relaxed text-foreground/80">{renderInline(line.slice(2))}</li>);
    } else if (isNumbered) {
      listBuf.push(<li key={i} className="text-sm leading-relaxed text-foreground/80 list-decimal">{renderInline(line.replace(/^\d+\.\s/, ""))}</li>);
    } else if (line.trim() === "") {
      nodes.push(<div key={i} className="h-2" />);
    } else {
      nodes.push(<p key={i} className="text-sm leading-relaxed text-foreground/80">{renderInline(line)}</p>);
    }
  });
  flushList();

  return (
    <div className="prose-sm max-w-none">
      {nodes}
      {streaming && <span className="inline-block w-0.5 h-4 bg-primary animate-pulse ml-0.5 align-text-bottom" />}
    </div>
  );
}

// ─── Export helpers ────────────────────────────────────────────────────────────
function mdToHtmlBody(text: string): string {
  return text
    .split("\n")
    .map(line => {
      const esc = (s: string) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
      const bold = (s: string) => esc(s).replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>");
      if (line.startsWith("# "))   return `<h1>${bold(line.slice(2))}</h1>`;
      if (line.startsWith("## "))  return `<h2>${bold(line.slice(3))}</h2>`;
      if (line.startsWith("### ")) return `<h3>${bold(line.slice(4))}</h3>`;
      if (line.startsWith("- ") || line.startsWith("* ")) return `<li>${bold(line.slice(2))}</li>`;
      if (/^\d+\.\s/.test(line))   return `<li>${bold(line.replace(/^\d+\.\s/, ""))}</li>`;
      if (line.trim() === "")      return "<br>";
      return `<p>${bold(line)}</p>`;
    })
    .join("\n");
}

function buildDocHtml(title: string, date: string, summary: string): string {
  return `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>${title}</title>
<style>
  body { font-family: Calibri, Arial, sans-serif; margin: 48px; color: #111; line-height: 1.65; font-size: 11pt; }
  h1 { font-size: 18pt; color: #111; border-bottom: 2px solid #e91e8c; padding-bottom: 6px; margin-bottom: 4px; }
  h2 { font-size: 13pt; color: #1a1a2e; margin-top: 22px; margin-bottom: 6px; }
  h3 { font-size: 11pt; color: #333; margin-top: 14px; margin-bottom: 4px; }
  p  { margin: 6px 0; }
  li { margin: 4px 0 4px 20px; }
  ul, ol { padding-left: 0; }
  .meta { color: #888; font-size: 9pt; margin-bottom: 24px; }
  .brand { color: #e91e8c; font-weight: bold; }
</style>
</head>
<body>
<h1>${title}</h1>
<p class="meta">Generated by <span class="brand">AdSpot AI</span> &nbsp;·&nbsp; ${date}</p>
${mdToHtmlBody(summary)}
</body>
</html>`;
}

function downloadDoc(title: string, summary: string) {
  const date = new Date().toLocaleDateString("en-NG", { day: "numeric", month: "long", year: "numeric" });
  const html  = buildDocHtml(title, date, summary);
  const blob  = new Blob([html], { type: "application/msword" });
  const url   = URL.createObjectURL(blob);
  const a     = document.createElement("a");
  a.href      = url;
  a.download  = `${title.replace(/\s+/g, "_")}.doc`;
  a.click();
  URL.revokeObjectURL(url);
}

function openPrintWindow(title: string, summary: string) {
  const date = new Date().toLocaleDateString("en-NG", { day: "numeric", month: "long", year: "numeric" });
  const html  = buildDocHtml(title, date, summary).replace(
    "</style>",
    `  @media print { body { margin: 20px; } .no-print { display: none; } }\n</style>`
  );
  const win = window.open("", "_blank", "width=900,height=700");
  if (!win) return;
  win.document.write(html + `<script>window.onload=function(){window.print();}</scr" + "ipt>`);
  win.document.close();
}

// ─── Main component ────────────────────────────────────────────────────────────
export function AISummaryButton({ adId, adTitle }: Props) {
  const [open, setOpen]           = useState(false);
  const [summary, setSummary]     = useState("");
  const [streaming, setStreaming] = useState(false);
  const [error, setError]         = useState<string | null>(null);
  const generatedAt               = useRef<Date | null>(null);
  const abortRef                  = useRef<AbortController | null>(null);

  const panelTitle = adId
    ? `${adTitle ?? "Ad"} — Analytics Summary`
    : "Campaign Portfolio Summary";

  const generate = useCallback(async () => {
    abortRef.current?.abort();
    const ac = new AbortController();
    abortRef.current = ac;

    setSummary("");
    setError(null);
    setStreaming(true);
    generatedAt.current = new Date();

    try {
      const data = await customFetch<{ summary?: string; content?: string } | string>(
        "/api/brands/analytics/ai-summary",
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ adId }),
          signal: ac.signal,
        } as RequestInit,
      );

      if (typeof data === "string") {
        setSummary(data);
      } else if (data && typeof data === "object") {
        setSummary(data.summary ?? data.content ?? JSON.stringify(data));
      }
    } catch (err) {
      if ((err as Error).name !== "AbortError") {
        setError(err instanceof Error ? err.message : "Generation failed — please try again");
      }
    } finally {
      setStreaming(false);
    }
  }, [adId]);

  const handleOpen = () => {
    setOpen(true);
    if (!summary && !streaming) generate();
  };

  return (
    <>
      <Button variant="outline" onClick={handleOpen} className="gap-2">
        <Sparkles className="w-4 h-4 text-[#e91e8c]" />
        Generate AI Summary
      </Button>

      <Sheet open={open} onOpenChange={v => { if (!v) abortRef.current?.abort(); setOpen(v); }}>
        <SheetContent side="right" className="w-[540px] max-w-full flex flex-col p-0 gap-0">

          {/* Header */}
          <div className="px-6 py-4 border-b flex items-center justify-between shrink-0 bg-gradient-to-r from-[#e91e8c]/5 to-transparent">
            <div className="flex items-center gap-2.5">
              <div className="w-7 h-7 rounded-full bg-[#e91e8c]/10 flex items-center justify-center">
                <Sparkles className="w-3.5 h-3.5 text-[#e91e8c]" />
              </div>
              <div>
                <h2 className="text-[13px] font-bold text-foreground leading-tight">AI Analytics Summary</h2>
                <p className="text-[10px] text-muted-foreground">{panelTitle}</p>
              </div>
            </div>
            {!streaming && summary && (
              <Button variant="ghost" size="sm" onClick={generate} className="gap-1.5 text-xs h-7 px-2">
                <RefreshCw className="w-3 h-3" />
                Regenerate
              </Button>
            )}
          </div>

          {/* Body */}
          <div className="flex-1 overflow-y-auto px-6 py-5">
            {streaming && !summary && (
              <div className="flex flex-col items-center justify-center h-40 gap-3">
                <div className="relative w-10 h-10">
                  <div className="absolute inset-0 rounded-full border-2 border-[#e91e8c]/20 animate-ping" />
                  <div className="w-10 h-10 rounded-full bg-[#e91e8c]/10 flex items-center justify-center">
                    <Sparkles className="w-4 h-4 text-[#e91e8c] animate-pulse" />
                  </div>
                </div>
                <p className="text-sm text-muted-foreground">Generating AI summary…</p>
                <p className="text-xs text-muted-foreground/60">Analysing your campaign data</p>
              </div>
            )}

            {error && (
              <div className="flex items-start gap-3 p-4 rounded-lg bg-destructive/10 border border-destructive/20 text-sm text-destructive">
                <AlertCircle className="w-4 h-4 mt-0.5 shrink-0" />
                <div>
                  <p className="font-medium">Generation failed</p>
                  <p className="text-xs mt-0.5 opacity-80">{error}</p>
                </div>
              </div>
            )}

            {summary && (
              <RenderSummary text={summary} streaming={streaming} />
            )}
          </div>

          {/* Footer — export buttons */}
          {summary && !streaming && (
            <div className="px-6 py-4 border-t bg-muted/30 shrink-0">
              <p className="text-[10px] text-muted-foreground mb-3">
                Generated {generatedAt.current?.toLocaleString("en-NG")} · Powered by AdSpot AI
              </p>
              <div className="flex gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  className="gap-1.5 flex-1"
                  onClick={() => downloadDoc(panelTitle, summary)}
                >
                  <Download className="w-3.5 h-3.5" />
                  Download as Word
                </Button>
                <Button
                  size="sm"
                  className="gap-1.5 flex-1 bg-[#e91e8c] hover:bg-[#c91570] text-white"
                  onClick={() => openPrintWindow(panelTitle, summary)}
                >
                  <Printer className="w-3.5 h-3.5" />
                  Save as PDF
                </Button>
              </div>
            </div>
          )}
        </SheetContent>
      </Sheet>
    </>
  );
}
